apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: simple-chart
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./clusters/ap-pe-eus2-cluster/apps/simple-chart/chart
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: fleet
        namespace: flux-system
  interval: 5m
  targetNamespace: default
